
!include r-pkg.yaml
---
- package: R module prodlim
  name: prodlim
  rpkgname: prodlim
  version: "{{versions.prodlim}}"
  baseurl: https://cran.r-project.org/src/contrib
  src_tarball: "{{rpkgname}}_{{version}}.{{extension}}"
  vendor_source: "{{baseurl}}/{{rpkgname}}_{{version}}.{{extension}}"
  requires:
    - R_3.6.2
    - R_3.6.2-Rcpp
    - R_3.6.2-lava
    - R_3.6.2-numDeriv
    - R_3.6.2-SQUAREM
