# Copyright (c) 2000 - 2019 The Regents of the University of California.
# All rights reserved.	
# This includes the Generic yaml2rpm Makefile - most packaging should
# be able to use this.
ALL_TARGETS = all
include $(YAML2RPM_HOME)/sys/Makefile

SHELL = /bin/bash

.PHONY: force

## when cleaning temporary yaml files, figure out which ones to not remove
KEEPYAMLS0 = $(shell cat modules.bootstrap.base | grep -v '^\#' )
KEEPYAMLS0 += $(shell cat keepyamls | grep -v '^\#' )
KEEPYAMLS0 += r-pkg R_versions
KEEPYAMLS = $(patsubst %,%.yaml,$(KEEPYAMLS0))
TMPYAMLS0 = $(wildcard *.yaml)
TMPYAMLS = $(filter-out $(KEEPYAMLS),$(TMPYAMLS0))

RVERSION = $(shell grep ^R: $(BASE_VERSION_FILE) | awk -F \" '{print $$2}')
all: R_versions.yaml.base modules.bootstrap versions.yaml bootstrap R_versions.yaml prep 
	make -f Makefile$(MAKEFILE_SUFFIX) BOOTSTRAP_MODULES_FILE=modules.bootstrap2 bootstrap
	make -f Makefile$(MAKEFILE_SUFFIX) modules.manifest
        
R_versions.yaml.base: force
	cat $(BASE_VERSION_FILE) $@.common > $@

prep: modules.build 
	./downloadpkg.py

builddeps.yaml: modules.desired deps.R
	( module load R/$(RVERSION); \
	  cat deps.R | R --slave > $@  )

R_versions.yaml: outversions.yaml R_versions.yaml.base
	rm -rf versions.yaml
	cat outversions.yaml $@.base > $@
	cat outversions.yaml $@.base > versions.yaml
	

versions.yaml: 
	cat R_versions.yaml.base > $@

buildorder outversions.yaml: builddeps.yaml 
	./depend.py > buildorder

modules.bootstrap2: buildorder 
	cat modules.bootstrap.base buildorder  > modules.bootstrap2

modules.bootstrap:
	cat $@.base > $@

modules.build: modules.bootstrap2 
	cat modules.bootstrap2 > $@

manifest: modules.manifest

modules.manifest: force
	cat modules.bootstrap2 >$@
	
freeze: R_versions.yaml force
	echo "freezing all yaml files, bootstrap files, buildorder into freeze subdir $(FREEZE_DIR)"
	if [ ! -d $(FREEZE_DIR) ]; then mkdir $(FREEZE_DIR); fi
	cp -p *base* *yaml *bootstrap* modules.manifest modules.build buildorder $(FREEZE_DIR) 
clean:
	-/bin/rm modules.bootstrap modules.bootstrap2 modules.build
	-/bin/rm $(TMPYAMLS)
	-/bin/rm buildorder
	-/bin/rm builddeps.yaml 
	
veryclean:
	-/bin/rm builddeps.yaml
