
!include r-pkg.yaml
---
- package: R module pkgconfig
  name: pkgconfig
  version: "{{ versions.pkgconfig }}"
  src_tarball: "{{name}}_{{version}}.{{extension}}"
  vendor_source: https://cran.r-project.org/src/contrib/{{name}}_{{version}}.tar.gz 
